
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author partho
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        jLabel4.setText("<html>Select the number<br> of literals</html>");
        literal_number_jCombobox.setSelectedIndex(1);
        
        patternize_text_field patternizer=new patternize_text_field();
        patternizer.capitalize(expression_field_1);
        patternizer.capitalize(expression_field_2);
        patternizer.capitalize(get_single_expression_dialogue_text_field);
        
        message_box.setBounds(0,0,400,220);
        message_box.setLocationRelativeTo(this);
        
        
        single_truth_table_dialog.setBounds(0,0,600,350);
        single_truth_table_dialog.setLocationRelativeTo(this);
        
        String instructionString="<html>1.Use only SOP form. Don't use any bracket<br>2.Write <b>A bar as !A</b> and <b>B bar as !B</b><br>Example: <b>A+A bar+A * B bar</b> is to write as <b>A+!A+A!B</b></html>";
        
        instruction_label.setText(instructionString);
    }
    
    public String expression1,expression2;
    public String regExpString="(!*[A-Z]+[!+]*[A-Z]*)+";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        message_box = new javax.swing.JDialog();
        message_box_jLabel1 = new javax.swing.JLabel();
        message_box_ok_button = new javax.swing.JButton();
        get_single_expression_dialogue = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        get_single_expression_dialogue_text_field = new javax.swing.JTextField();
        get_single_expression_dialogue_ok_button = new javax.swing.JButton();
        get_single_expression_dialogue_cancel_button = new javax.swing.JButton();
        single_truth_table_dialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        instruction_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        expression_field_1 = new javax.swing.JTextField();
        expression_field_2 = new javax.swing.JTextField();
        compareButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        literal_number_jCombobox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        message_box.setTitle("Notice");
        message_box.setResizable(false);

        message_box_jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        message_box_ok_button.setText("Ok");
        message_box_ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                message_box_ok_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout message_boxLayout = new javax.swing.GroupLayout(message_box.getContentPane());
        message_box.getContentPane().setLayout(message_boxLayout);
        message_boxLayout.setHorizontalGroup(
            message_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(message_boxLayout.createSequentialGroup()
                .addGroup(message_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(message_boxLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(message_box_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(message_boxLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(message_box_ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        message_boxLayout.setVerticalGroup(
            message_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(message_boxLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(message_box_jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message_box_ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        get_single_expression_dialogue.setTitle("Single Expression");
        get_single_expression_dialogue.setResizable(false);

        jLabel1.setText("Enter a logic expression in SOP form");

        get_single_expression_dialogue_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_single_expression_dialogue_text_fieldActionPerformed(evt);
            }
        });

        get_single_expression_dialogue_ok_button.setText("OK");
        get_single_expression_dialogue_ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_single_expression_dialogue_ok_buttonActionPerformed(evt);
            }
        });

        get_single_expression_dialogue_cancel_button.setText("Cancel");
        get_single_expression_dialogue_cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_single_expression_dialogue_cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout get_single_expression_dialogueLayout = new javax.swing.GroupLayout(get_single_expression_dialogue.getContentPane());
        get_single_expression_dialogue.getContentPane().setLayout(get_single_expression_dialogueLayout);
        get_single_expression_dialogueLayout.setHorizontalGroup(
            get_single_expression_dialogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(get_single_expression_dialogueLayout.createSequentialGroup()
                .addGroup(get_single_expression_dialogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(get_single_expression_dialogueLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(get_single_expression_dialogueLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(get_single_expression_dialogue_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(get_single_expression_dialogueLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(get_single_expression_dialogue_ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(get_single_expression_dialogue_cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        get_single_expression_dialogueLayout.setVerticalGroup(
            get_single_expression_dialogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(get_single_expression_dialogueLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(get_single_expression_dialogue_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(get_single_expression_dialogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(get_single_expression_dialogue_ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_single_expression_dialogue_cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout single_truth_table_dialogLayout = new javax.swing.GroupLayout(single_truth_table_dialog.getContentPane());
        single_truth_table_dialog.getContentPane().setLayout(single_truth_table_dialogLayout);
        single_truth_table_dialogLayout.setHorizontalGroup(
            single_truth_table_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(single_truth_table_dialogLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        single_truth_table_dialogLayout.setVerticalGroup(
            single_truth_table_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(single_truth_table_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boolean Expression Comparator");
        setResizable(false);

        instruction_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Expression 1:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Expression 2:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        expression_field_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expression_field_1ActionPerformed(evt);
            }
        });

        compareButton.setText("Compare");
        compareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareButtonActionPerformed(evt);
            }
        });

        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        literal_number_jCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));

        jLabel5.setText("Instruction");

        jMenu3.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        jMenu1.setText("More");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Truth Table for single expressiom");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("About");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("This Software");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Developer");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(literal_number_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(expression_field_2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addComponent(expression_field_1)
                    .addComponent(instruction_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(compareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(528, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(instruction_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(expression_field_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(literal_number_jCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expression_field_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(compareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(168, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expression_field_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expression_field_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expression_field_1ActionPerformed

    private void compareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareButtonActionPerformed
        expression1=expression_field_1.getText();
        expression2=expression_field_2.getText();
        
        
        
        patternize_text_field patternizer=new patternize_text_field();
        
        if(!patternizer.isRegular(expression1,regExpString)){
            //check expression 1 validity
            message_box.setVisible(true);
            message_box.setTitle("Compare Logical Expression");
            message_box_jLabel1.setText("Invalid Expression 1");
        }
        else{
            //check expression 2 validity
            if(!patternizer.isRegular(expression2, regExpString)){
                message_box.setVisible(true);
                message_box.setTitle("Compare Logical Expression");
                message_box_jLabel1.setText("Invalid Expression 2");
            }
            else{
                //check literal number
                Library getLibrary=new Library();
                int literalNumber_in_expression=getLibrary.numberOfLiteral(expression1, expression2);
                int literal_num_seleted=Integer.parseInt(String.valueOf(literal_number_jCombobox.getSelectedItem()));
                if(literalNumber_in_expression!=literal_num_seleted){
                    message_box.setVisible(true);
                    message_box_jLabel1.setForeground(Color.red);
                    message_box.setTitle("Compare Logical Expression");
                    message_box_jLabel1.setText("<html>You selected literal number "+literal_num_seleted+"<br>But used "+literalNumber_in_expression+" literals</html>");
                }
                else{
                    //start working 
                    if(getLibrary.isEqual(expression1, expression2)){
                        //instruction_label.setText("equal");
                        message_box_jLabel1.setText("Expressions are Equal");
                        message_box.setTitle("Compare Logical Expression");
                        message_box_jLabel1.setForeground(Color.BLUE);
                        message_box.setVisible(true);
                    }
                    else{
                        //instruction_label.setText("Not equal");
                        message_box_jLabel1.setText("Expressions are not Equal");
                        message_box.setTitle("Compare Logical Expression");
                        message_box_jLabel1.setForeground(Color.red);
                        message_box.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_compareButtonActionPerformed

    private void message_box_ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_message_box_ok_buttonActionPerformed
        message_box.dispose();
    }//GEN-LAST:event_message_box_ok_buttonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void get_single_expression_dialogue_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_single_expression_dialogue_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_get_single_expression_dialogue_text_fieldActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        get_single_expression_dialogue.setBounds(0,0,550,220);
        get_single_expression_dialogue.setLocationRelativeTo(this);
        
        get_single_expression_dialogue.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void get_single_expression_dialogue_cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_single_expression_dialogue_cancel_buttonActionPerformed
        get_single_expression_dialogue.dispose();
    }//GEN-LAST:event_get_single_expression_dialogue_cancel_buttonActionPerformed

    private void get_single_expression_dialogue_ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_single_expression_dialogue_ok_buttonActionPerformed
        String single_expression=get_single_expression_dialogue_text_field.getText();
        
        patternize_text_field patternizer=new patternize_text_field();
        
        if( !(patternizer.isRegular(single_expression, regExpString)) ){
            message_box_jLabel1.setText("<html>Invalid expression.<br>See the instructions please</html>");
            message_box.setVisible(true);
        }
        else{
            Library getLibrary=new Library();
            single_truth_table_dialog.setVisible(true);
            DefaultTableModel tableModel=(DefaultTableModel) jTable1.getModel();
            
            
            single_truth_table_dialog.setTitle(single_expression);
            getLibrary.generateTruthTable(jTable1, single_expression);
        }
    }//GEN-LAST:event_get_single_expression_dialogue_ok_buttonActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        message_box.setTitle("About Developer");
        String message_string="<html><b>Developed By: </b>Partho Protim Mondal<br>";
        message_string+="<b>Studying: </b>Department of Electrical And Electronic Engineering,University Of Dhaka<br>";
        message_string+="<b>Email: </b>partho8181bd@gmail.com<br>";
        message_string+="<b>Phone:</b> +8801781603405</html>";
        message_box.setBounds(0,0,430,200);
        message_box_jLabel1.setText(message_string);
        message_box.setLocationRelativeTo(this);
        message_box.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        message_box.setTitle("Version: 1.1");
        String message_string="<html>As the first version, this software may have few bugs.<br>";
        message_string+="Any suggestion to develop the software will be appreciated.<br>";
        message_string+="And you may give new idea<br>";
        message_string+="Please see <b> Developer</b> option to contact developer</html>";
        message_box.setBounds(0,0,430,200);
        message_box_jLabel1.setText(message_string);
        message_box.setLocationRelativeTo(this);
        message_box.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compareButton;
    private javax.swing.JTextField expression_field_1;
    private javax.swing.JTextField expression_field_2;
    private javax.swing.JDialog get_single_expression_dialogue;
    private javax.swing.JButton get_single_expression_dialogue_cancel_button;
    private javax.swing.JButton get_single_expression_dialogue_ok_button;
    private javax.swing.JTextField get_single_expression_dialogue_text_field;
    private javax.swing.JLabel instruction_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> literal_number_jCombobox;
    private javax.swing.JDialog message_box;
    private javax.swing.JLabel message_box_jLabel1;
    private javax.swing.JButton message_box_ok_button;
    private javax.swing.JDialog single_truth_table_dialog;
    // End of variables declaration//GEN-END:variables
}
